server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: products-service
          uri: ${PRODUCTS_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/products/**

        - id: categories-service
          uri: ${CATEGORIES_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/categories/**

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.web.reactive]': DEBUG
    '[reactor.netty.http.client]': DEBUG